# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d8f7bfc41e033bbac1b520dd2718fbce3a489de106c6cb7e5cb84facee72086c74de908f457259960a4802ea3a005a6b4aa0c3eeca9e565efa64f2f44bd5f114

test:
  secret_key_base: 75037685e0ea3b534edcd9cc4b263e6d43de4f63baffbb3bea342123a587b8131c1eab5db4fa46e047ea5c03b6d36fb28abfb261f3328d43a65b914d8a1766a5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
